#ifndef SERVER_GLOBALCONFIG_H
#define SERVER_GLOBALCONFIG_H

#define NUMBER_OF_PLAYERS 4
#define MAX_NUMBER_OF_BEASTS 25
#define TIME_PRE_TICK 500000

#define MAP_SIZE_X 51
#define MAP_SIZE_Y 25
#define MAP_INTERFACE_OFFSET 3

#define PLAYER_VIEW_RANGE 2

#define WALL L'█'
#define BUSH L'#'
#define BEAST L'*'
#define COIN L'c'
#define TREASURE L't'
#define LARGE_TREASURE L'T'
#define DROPPED_TREASURE L'D'
#define CAMPSITE L'A'
#define EMPTY L' '

#define BEAST_TEXT_COLOR COLOR_RED
#define COIN_TEXT_COLOR COLOR_BLACK
#define TREASURE_TEXT_COLOR COLOR_BLACK
#define LARGE_TREASURE_TEXT_COLOR COLOR_BLACK
#define DROPPED_TREASURE_TEXT_COLOR COLOR_BLACK
#define CAMPSITE_TEXT_COLOR COLOR_YELLOW
#define PLAYER_TEXT_COLOR COLOR_WHITE

#define BEAST_BG_COLOR COLOR_BLACK
#define COIN_BG_COLOR COLOR_YELLOW
#define TREASURE_BG_COLOR COLOR_YELLOW
#define LARGE_TREASURE_BG_COLOR COLOR_YELLOW
#define DROPPED_TREASURE_BG_COLOR COLOR_YELLOW
#define CAMPSITE_BG_COLOR COLOR_GREEN
#define PLAYER_BG_COLOR COLOR_MAGENTA

#define BEAST_COLOR 1
#define COIN_COLOR 2
#define TREASURE_COLOR 3
#define LARGE_TREASURE_COLOR 4
#define DROPPED_TREASURE_COLOR 5
#define CAMPSITE_COLOR 6
#define PLAYER_COLOR 7

extern int myPid;
extern int inColor;

void initConfig();

#endif //SERVER_GLOBALCONFIG_H
